package com.farmer.labour.collabaration.farmerlabour.controller;

import java.security.Principal;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.farmer.labour.collabaration.farmerlabour.model.FarmerLabourUser;
import com.farmer.labour.collabaration.farmerlabour.utility.JwtUtil;
import  com.farmer.labour.collabaration.farmerlabour.model.UserRequest;
import  com.farmer.labour.collabaration.farmerlabour.model.UserResponse;
import com.farmer.labour.collabaration.farmerlabour.service.interfaces.UserServiceInf;

@RestController
@RequestMapping("/user")
public class UserController {
    
    @Autowired
    UserServiceInf userServiceInf;

    @Autowired
    AuthenticationManager authenticationManager;
    
    @Autowired
	private JwtUtil jwtUtil;

    /* save basic farmerLabourUserDetails */
    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody FarmerLabourUser user){
        Integer userId= userServiceInf.save(user);
        String body="user : "+userId+" saved !!";
        return ResponseEntity.ok(body);
    }
    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
        // for this authentication amangeer already we told to get userr from data base ( loaduserby username)
        // compare passed user details with security userr details
        //in security config class we told this info
        System.out.println("user name is: "+userRequest.getUsername());
        authenticationManager.authenticate(
            new UsernamePasswordAuthenticationToken(
                    userRequest.getUsername(), 
                    userRequest.getPassword()
                    )
            );
    String token=jwtUtil.generateToken(userRequest.getUsername());
    return ResponseEntity.ok(new UserResponse(token,"GENERATED BY Maldanna"));
    }

    @PostMapping("/update")
    public ResponseEntity<String> updateUser(@RequestBody FarmerLabourUser user){
        return ResponseEntity.ok("user updated successfully");
    }

    @PostMapping("/getuser")
    public ResponseEntity<FarmerLabourUser> getUser(@RequestBody String userName ){
        FarmerLabourUser resUser=null;
        return ResponseEntity.ok(resUser);
    }

    @PostMapping("/getAlluser")
    public ResponseEntity<List<FarmerLabourUser>> getAllUsers(@RequestBody String userName ){
        List<FarmerLabourUser> resUsers=null;
        return ResponseEntity.ok(resUsers);
    }

    @PostMapping("/delete")
    public ResponseEntity<String> deleteUser(@RequestBody String userName ){
        String result=null;
        return ResponseEntity.ok(result);
    }



    @GetMapping("/welcome")
	public ResponseEntity<String> accessUserData() {
		return ResponseEntity.ok("Hello user");
	}

    
    
}
